name: flutter_barsalutemple
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_database: ^4.4.0
  firebase_core: ^0.5.3
  share: ^0.6.5+4
  url_launcher: ^5.7.10
  android_intent_plus: ^3.1.6
  package_info: ^0.4.0+13
  cached_network_image: ^2.3.3
  firebase_messaging: ^7.0.3
  maps_launcher: ^1.2.2+2
  dio: ^3.0.9
  flutter_secure_storage: ^3.3.5
  intl: ^0.16.1
  shape_of_view: ^1.0.2
  firebase_storage: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/about.png
      - assets/images/otherapp.png
      - assets/images/share.png
      - assets/images/suggestion.png
      - assets/images/villages.png
      - assets/images/dharamshala.png
      - assets/images/history.png
      - assets/images/rateus.png
      - assets/images/ic_yoga.png
      - assets/images/ic_fitme.png
      - assets/images/ic_meme.png
      - assets/images/ic_zero.png
      - assets/images/ic_abhi.png
      - assets/images/placeholder.png
      - assets/images/ic_news.png
      - assets/images/map.png
      - assets/images/img_splash.jpeg
      - assets/images/heart.png
      - assets/images/back2.jpg
      - assets/images/instagram.png
      - assets/images/forb.jpeg
      - assets/images/temple.png
      - assets/images/rupees.png
      - assets/images/rupee.png
      - assets/images/photos.png
      - assets/images/video.png
      - assets/images/team.png
      - assets/images/cal.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: YatraOne
       fonts:
         - asset: assets/fonts/YatraOne-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Montserrat
       fonts:
        - asset: assets/fonts/Bold.ttf
          weight: 900
        - asset: assets/fonts/Medium.ttf
          weight: 700
        - asset: assets/fonts/Regular.ttf
          weight: 400
        - asset: assets/fonts/Light.ttf
          weight: 200

     - family: Rye
       fonts:
         - asset: assets/fonts/Rye-Regular.ttf

     - family: Spirax
       fonts:
         - asset: assets/fonts/Spirax-Regular.ttf

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
